public enum SoundKeys
{
    _None,
    music,
    ui_button_click_positive,
    ui_button_click_negative,
    ambient,
    ui_button_hover,
    ui_currency_gain,
    ui_TTnode_click,
    ui_TTnode_maxlevel,
    SFX_Woosh,
    SFX_Groan,
    SFX_Impact,
    SFX_Destruction,
    SFX_Impact_Magic,
    SFX_CrowdCheer,
    sfx_block
}
