using System.Collections.Generic;
using UnityEngine;

namespace nickeltin.SDF.Runtime.DecoupledPipeline
{
    /// <summary>
    /// Main asset for files with extension *.sdfasset
    /// This asset decouples sdf import pipeline, makes all generated sdf content a separate asset.
    /// </summary>
    public class SDFAsset : ScriptableObject
    {
        [SerializeField] internal List<SDFSpriteMetadataAsset> _spriteMetadataAssets = new();
        
        public IReadOnlyList<SDFSpriteMetadataAsset> SpriteMetadataAssets => _spriteMetadataAssets;
        
        /// <summary>
        /// Will try to find meta-asset for either sdf sprite generated from this asset
        /// or from source sprite that is part of the texture generated by unity.
        /// </summary>
        public bool TryGetSpriteMetadataAsset(Sprite sourceOrSDFSprite, out SDFSpriteMetadataAsset metadataAsset)
        {
            metadataAsset =_spriteMetadataAssets.Find(asset =>
                asset.Metadata.SourceSprite == sourceOrSDFSprite || asset.Metadata.SDFSprite == sourceOrSDFSprite);
            return metadataAsset != null;
        }
    }
}